Explicitly require the logger gem and set autoload
ActuveSupport 7.0 seems to have a bug in its initialization process.

```
NameError: uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger (NameError)
```